### PR TITLE
[PPP-3514] Use of vulnerable components - jquery - multiple versions …

### PR DESCRIPTION
**Pull request by mchen-len-son**
…1.x prior to 1.12

- updated jquery version to 1.12.4

### CODE REVIEW

**Comment by pamval** [comment]
@jvelasques @afrjorge please review

**Comment by jvelasques** [comment]
@mchen-len-son have you ran the build successfully? 
The tests do not pass on my machine, particularly the pentaho-js ones.

**Comment by mchen-len-son** [comment]
@jvelasques 
I also see errors in system out when running js tests, but eventually the PhantomJS resulting xml contains no errors, no failures.

Which one exactly is failing, or there are a lot of them?

**Comment by jvelasques** [comment]
6 tests in the Table Component are failing.
example:
*ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'*
*PhantomJS 1.9.8 (Linux 0.0.0) The Table Component # properly escapes column headers FAILED*

**Comment by afrjorge** [comment]
@jvelasques @mchen-len-son changing into your branch mchen-len-son@273f711806c92b137fc240a70f42f604d3742e2c and executing **mvn clean install** on the CDF root folder also gives me the following errors:
```
[INFO] --- frontend-maven-plugin:0.0.26:karma (javascript-tests) @ cdf-pentaho-js ---
[INFO] Running 'karma start /Users/ajorge/Pentaho/ctools/cdf/pentaho-js/src/test/javascript/config/karma.ci.conf.js --no-colors' in /Users/ajorge/Pentaho/ctools/cdf/pentaho-js
       ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'
       PhantomJS 1.9.8 (Mac OS X 0.0.0) The Table Component # allows a dashboard to execute update FAILED
[INFO] 	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'
       PhantomJS 1.9.8 (Mac OS X 0.0.0) The Table Component # properly escapes column headers FAILED
[INFO] 	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'
       PhantomJS 1.9.8 (Mac OS X 0.0.0) The Table Component # ignores null column headers FAILED
[INFO] 	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       ERROR: '[error] WD: Error processing component:Unable to parse JSON string'
       ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'
       PhantomJS 1.9.8 (Mac OS X 0.0.0) The Table Component # executes with a empty result set and column types ,column widths ,column sortable and column searchable properties defined. FAILED
[INFO] 	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'
       PhantomJS 1.9.8 (Mac OS X 0.0.0) The Table Component # executes with a result set that has less columns than column types ,column widths ,column searchable and column sortable properties defined. FAILED
[INFO] 	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       ERROR: '[error] WD: TypeError: 'undefined' is not a function (evaluating 'word.charAt(0)')'
       PhantomJS 1.9.8 (Mac OS X 0.0.0) The Table Component # executes with a result set that has more columns than column types ,column widths ,column searchable and column sortable properties defined FAILED
[INFO] 	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 37 of 37 (6 FAILED) (33.712 secs / 31.452 secs)
[ERROR] .write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] cdf-plugin ......................................... SUCCESS [  3.126 s]
[INFO] cdf-core ........................................... SUCCESS [ 12.995 s]
[INFO] cdf-core-js ........................................ SUCCESS [01:06 min]
[INFO] cdf-pentaho ........................................ SUCCESS [02:30 min]
[INFO] cdf-pentaho-js ..................................... FAILURE [ 51.259 s]
[INFO] cdf-plugin-assemblies .............................. SKIPPED
[INFO] pentaho-cdf-js ..................................... SKIPPED
[INFO] pentaho-cdf ........................................ SKIPPED
[INFO] pentaho-cdf-samples ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:44 min
[INFO] Finished at: 2016-06-27T18:56:01+01:00
[INFO] Final Memory: 84M/571M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:karma (javascript-tests) on project cdf-pentaho-js: Failed to run task: 'karma start /Users/ajorge/Pentaho/ctools/cdf/pentaho-js/src/test/javascript/config/karma.ci.conf.js --no-colors' failed. (error code 1) -> [Help 1]
```
Ideally, you should also check that the CDF and CDE samples execute correctly.

**Comment by mchen-len-son** [comment]
I found the reason of test failures.
The solution is upgrade of jQuery.DataTables version to at least 1.10.7.

The main issue is that I somehow didn’t really upgrade the jquery.datatables when was trying to fix the test failures, and therefore decided, that it would not help.
My mistake!

The issue is reproduced in PhantomJS only. And in IE8 (thanks to @kolinus and @YuryBY !).
Now, after deep investigation and debugging, I know [what exactly should fix the issue](https://github.com/DataTables/DataTables/commit/2176acf2fbde20b160d19593d334abb51160e47e), and after re-checking jquery.datatable upgrade, all the tests are passing.


So now we need to upgrade the jquery.datatables as well, at least to 1.10.7, where the fix is.
I used approved COMP-3220 and upgraded it for 1.10.12.

@jvelasques @afrjorge please re-check the changes. Now the tests are passing.

**Comment by mchen-len-son** [comment]
@jvelasques @afrjorge did you have a chance to take a look at the PR?

**Comment by mchen-len-son** [comment]
@jvelasques @afrjorge @pamval please review

**Comment by mchen-len-son** [comment]
@jvelasques @afrjorge did you have a chance to take a look at the PR?

**Comment by kolinus** [comment]
@pamval  @jvelasques @afrjorge could you please take a look at the PR?

**Comment by afrjorge** [comment]
I rebased to master, built successfully and ran some samples that make use of DataTable after replacing CDF in the Pentaho Server SNAPSHOT build 421. Validated that the versions are correct by executing:
`require("cdf/lib/jquery").fn.jquery` => `1.12.4`
`require("cdf/lib/jquery").fn.dataTable.fnVersionCheck("1.10.12")` => `true`
This does need more QA validation due to libraries sometime introducing breaking changes in minor releases.

@mchen-len-son to rebase you will need to keep the following code:
```
  //Google Caja HTML Sanitizer 0.1.3 with dependencies
  requirePaths['cdf/lib/sanitizer/lib/html4'] = prefix + '/sanitizer/lib/html4';
  requirePaths['cdf/lib/sanitizer/lib/uri'] = prefix + '/sanitizer/lib/uri';
  requirePaths['cdf/lib/sanitizer'] = prefix + '/sanitizer/sanitizer';

  //jquery 1.12.4, without globally scoped variables
```
The addition of sanitizer generated a conflict with your updated jquery line comment.
Please ignore wingman fails that read `Please, commit your changes or stash them before you can merge.`.

**Pull request closed without merging**
