### PR TITLE
Eric Hynds Multiselect lib updated

### PR DESCRIPTION
**Pull request by marpontes**
There was an issue with the latest versions of CDF and this JQuery
Multiselect plugin [Hynds].

If you had a multiselect rendered with this plugin, it would popup to
show the options on the visualization, but it would never hide again.

So the core js file was updated to its latest version and the dropdown
menu works like a charm.

### CODE REVIEW

**Comment by pamval** [comment]
To merge after 5.4 branching.

Needs a new component issue in jira due to external library update.

**Comment by shivasakthi18** [comment]
Any resolution for this. ?

**Comment by pamval** [comment]
The external library update has not been accepted on our internal external component process. We won't be processing this as is. We'll probably develop a way to allow external developers to plug different types of selectors - That will be acceptable, but we're not able to bundle this new version in product.

**Comment by pamval** [comment]
see http://jira.pentaho.com/browse/CDF-790 for reference

**Pull request closed without merging**
