### PR TITLE
[CDF-667] - Adding root id option to a component with valuesArray

### PR DESCRIPTION
**Pull request by jvelasques**

### CODE REVIEW

**Comment by jvelasques** [comment]
@pamval @carlosrusso please review

**Comment by carlosrusso** [comment]
Please move the test to options.root.id to the updateModel method.
Also, please make the code a bit more idiomatic (boy scout rule), as the code still shows symptoms from the compilation from coffeescript

**Comment by pamval** [comment]
really ? You're complaining about the code that the tool **you chose by yourself and used** generates ?
And telling someone else to fix it ?

**Comment by jvelasques** [comment]
@pamval @carlosrusso changed accordingly, please review

**Comment by carlosrusso** [comment]
@pamval Yes, indeed I am complaining about my own mistakes. All I have in mind is the quality of the product.  Should I refrain from doing so?

**Pull request merged**
