### PR TITLE
[PPP-3450] - Backbone.js vulnerable to DOM XSS

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- upgrade backbone: 1.1.2 -> 1.2.3

@jvelasques, @afrjorge, @pamval, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pamval, can you please find someone to review the PR?
BTW, I forgot to link a CP ticket: http://jira.pentaho.com/browse/COMP-2614

**Comment by akhayrutdinov** [comment]
@pamval, review it please

**Comment by pamval** [comment]
@jvelasques, @afrjorge, also review this one

**Comment by jvelasques** [comment]
@pamval @afrjorge @akhayrutdinov this version of backbone has a hard dependency on underscore >= 1.7, we're using 1.6 still.

> Backbone's only hard dependency is Underscore.js ( >= 1.7.0). For RESTful persistence and DOM manipulation with Backbone.View, include jQuery ( >= 1.11.0)

Note that it also refers jQuery >= 1.11.0, we have jQuery at v1.9.1.

**Comment by pamval** [comment]
#816 supersedes this one

**Pull request closed without merging**
