### PR TITLE
[CDF-670] - As a dashboard developer using a TableComponent, I would …

### PR DESCRIPTION
**Pull request by eliofreitas**
…like to be able to provide a friendly error message when a query fails.

### CODE REVIEW

**Comment by eliofreitas** [comment]
@pamval please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core-js/pom.xml site
2. mvn -B -fn -DrunITs=true -f pentaho-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pentaho-js/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  core-js/src/main/javascript/cdf/queries/BaseQuery.js
  pentaho-js/src/main/javascript/cdf/components/TableComponent.js
  pentaho-js/src/test/javascript/cdf/components/TableComponent-spec.js

null

null

**Comment by pamval** [comment]
@eliofreitas:

Are we introducing a new property, failureCallback, to the Table Component ? 
If so, we must update the documentation at plugin samples -> CDF -> Documentation -> Reference.

We also need to decide on whether we want this property to be exposed in CDE.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core-js/pom.xml site
2. mvn -B -fn -DrunITs=true -f pentaho-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pentaho-js/pom.xml site
3. mvn -B -fn -DrunITs=true -f assemblies/cdf-samples/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f assemblies/cdf-samples/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
  assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
  core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
  core-js/src/main/javascript/cdf/queries/BaseQuery.js
  pentaho-js/src/main/javascript/cdf-legacy/components/table.js
  pentaho-js/src/main/javascript/cdf/components/TableComponent.js
  pentaho-js/src/test/javascript/cdf/components/TableComponent-spec.js

null

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core-js/pom.xml site
2. mvn -B -fn -DrunITs=true -f pentaho-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pentaho-js/pom.xml site
3. mvn -B -fn -DrunITs=true -f assemblies/cdf-samples/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f assemblies/cdf-samples/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
  assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
  core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
  core-js/src/main/javascript/cdf/queries/BaseQuery.js
  pentaho-js/src/main/javascript/cdf-legacy/components/table.js
  pentaho-js/src/main/javascript/cdf/components/TableComponent.js
  pentaho-js/src/test/javascript/cdf/components/TableComponent-spec.js

null

null

**Comment by eliofreitas** [comment]
@pamval updated, added the documentation also modified to the legacy version, working on the CDE exposure

**Pull request merged**
