### PR TITLE
[CDF-637], [CDF-639], [CDF-659] and [CDF-660] 

### PR DESCRIPTION
**Pull request by mfgaspar**
Revamp to template component and add 9 addins to it
Revamp to the template addin and solve a bug

### CODE REVIEW

**Comment by mfgaspar** [comment]
Pedro Value, I believe that this pull request should be in order.

**Comment by pamval** [comment]
These addIns are very similar to the table ones. They should be the same code with some (if any) customizations for each of the use cases.

@afrjorge review and make the necessary changes: Maybe a TrendArrowBase that is inherited by a TrendArrow for table and a TrendArrow for Template.

**Comment by mfgaspar** [comment]
[CDF-659] Revamp to the template addin: exposing a function for model parsing and also allow to customize messages as part of the options. Added to the pull request.

**Comment by mfgaspar** [comment]
[CDF-660] - Solved a bug to the template addin. The addin was not applying the formatters in the correct way and might produce an invalid template.

**Comment by afrjorge** [comment]
Please view https://github.com/webdetails/cdf/pull/633

**Pull request closed without merging**
