### PR TITLE
[SP-3772] Backport of CDF-986 - XSS vulnerability in Date Input Component (7.1 Suite)

### PR DESCRIPTION
**Pull request by Advent51**
- backport of #952

### CODE REVIEW

**Comment by Advent51** [comment]
@afrjorge @mchen-len-son @pamval please review

**Comment by mchen-len-son** [comment]
@afrjorge @pamval please merge this one. it'a already approved.
thanks.

**Comment by Advent51** [comment]
@kolinus please review

**Comment by mchen-len-son** [comment]
@duarteteixeira please merge this one. it'a already approved.
thanks.

**Pull request merged**
