### PR TITLE
[SP-1771] - Backport of PRD-5398 - Prompt screen flashes and take user b...

### PR DESCRIPTION
**Pull request by MikhailHubanau**
...ack to the top again (5.3 Suite)

store scroll position to cookie and restore after refresh

### CODE REVIEW

**Comment by MikhailHubanau** [comment]
@pamval @davidmsantos90 would you mind to review and merge?

**Comment by pamval** [comment]
@MikhailHubanau, I'm not sure this is the right place for this fix. This issue affects the prompting library only and not every CDF dashboard. 

Isn't there a  a change to prompting that we could try to fix this ?

**Comment by MikhailHubanau** [comment]
Fix for original issue https://github.com/webdetails/cdf/pull/421

**Comment by MikhailHubanau** [comment]
@pamval, I tested this fix with report attached in http://jira.pentaho.com/browse/PRD-5398.

I was trying to solve this issue on pentaho-platform-plugin-reporting side, but I had to move the solution on CDF layer, because CDF logic (in our case) wraps plugin-reporting code and discards efforts spent on plugin-reporting side. 

Does it make sense?

**Comment by MikhailHubanau** [comment]
Searching better solution.

**Pull request closed without merging**
