### PR TITLE
[CDE-944] Filter Component - the buttons that collapse groups don't work properly

### PR DESCRIPTION
**Pull request by ricardosilva88**
@pamval @diogofscmariano @afrjorge

### CODE REVIEW

**Comment by ricardosilva88** [comment]
@afrjorge ty for the feedback, I wasn't sure if legacy version also requires changes. I'll update the PR

**Comment by ricardosilva88** [comment]
@afrjorge legacy version added to PR

**Comment by afrjorge** [comment]
Seems that you fixed the CSS classes (`expanded` and `collapsed`) used in Group-template.html but you missed the ones in Root-template.html, Root-overlay.html, Root-skeleton.html and Root-header.html. There is also some logic in Root.js to toggle these CSS classes. Should any of these also be changed?
If not, then for the legacy version it seem there is a change missing in template.js: [link here](https://github.com/webdetails/cdf/blob/master/core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/templates.js#L35)

**Comment by ricardosilva88** [comment]
This problem doesn't affect any Root elements, just the group scope. That's why the change is localized to "group" only.

**Comment by afrjorge** [comment]
Then it seems this is only missing the legacy template change for "Group-template" in template.js.

**Comment by ricardosilva88** [comment]
@afrjorge done, PR updated

**Pull request merged**
