### PR TITLE
[CDF-609][CDF-641] - FilterComponent will now search server side. Accounting for when the query object does not exist.

### PR DESCRIPTION
**Pull request by jvelasques**

### CODE REVIEW

**Comment by jvelasques** [comment]
@pamval @carlosrusso please review

**Comment by pamval** [comment]
Aren't there tests covering this behavior ?

**Comment by carlosrusso** [comment]
The component doesn't need a query to run, it can use a .valuesArray, so the query object might not exist.

**Comment by jvelasques** [comment]
@pamval @carlosrusso @afrjorge, added unit tests, please review

**Comment by pamval** [comment]
backport to 5.x

**Pull request merged**
