### PR TITLE
[PPP-3455] - Dynamic code injection vulnerabilities found

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- replace eval() with JSON.parse()

@diogofscmariano, @dcleao, @pamval, review it please.
I found the library on github: https://github.com/simile-widgets/timeline
Looks like it is abandoned, hence I suppose it makes sense to fix it locally.

### CODE REVIEW

**Comment by pamval** [comment]
We need to add the original license to the header of these files (https://github.com/simile-widgets/timeline/blob/master/LICENSE.txt)
And then a comment saying we modified it.

**Comment by akhayrutdinov** [comment]
@pamval, do you mean adding the header to all files or just putting the txt file into the folder?

**Comment by pamval** [comment]
should be on the files :(

**Comment by akhayrutdinov** [comment]
@pamval, I've done it in the separate commit

**Pull request merged**
