### PR TITLE
[BACKLOG-21716] Create CDF webpackage and remove use of legacy global variables

### PR DESCRIPTION
**Pull request by nantunes**
@pentaho/millenniumfalcon please review.

### CODE REVIEW

**Comment by nantunes** [comment]
@webdetails/millenniumfalcon

**Comment by afrjorge** [comment]
Please notice that one commit has the CDE issue id BACKLOG-21718.

**Comment by davidmsantos90** [comment]
@afrjorge we will squash merge this, so it won't be a problem. Nevertheless thanks for noticing that it was the wrong BACKLOG issue

**Comment by davidmsantos90** [comment]
@webdetails/millenniumfalcon please review and merge if possible. CDE needs this PR to stop failing the build of cde-components

**Pull request merged**
