### PR TITLE
PDB-1830 - Regression: Dashboard Text Field prompt ignoring Width spe…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…cified

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@pamval 
Please review.

**Comment by pamval** [comment]
Aliaksandr, would be safer if we support both properties for setting width and maxChars.

Something like 

(myself.size ? ("' size='" + myself.size) : (myself.charWidth ?  ("' size='" + myself.charWidth : "" ) ).

This will avoid regressions. 
Ideally, we would output a log warning the user that size and maxLength are deprecated, if they are still using it.

**Comment by Aliaksandr-Kastenka** [comment]
Will update, please do not merge it. We got code freeze.

**Comment by Aliaksandr-Kastenka** [comment]
@pamval 
Please review.

**Pull request merged**
