### PR TITLE
[CDE-778] - Error in components when resultSet is empty and the 'Colu…

### PR DESCRIPTION
**Pull request by eliofreitas**
…mn Type' attribute is defined.

### CODE REVIEW

**Comment by eliofreitas** [comment]
@afrjorge @jvelasques

**Comment by eliofreitas** [comment]
Building pull request

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/32/

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pentaho-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pentaho-js/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact



Changed files:
==============
  pentaho-js/src/main/javascript/cdf/components/TableComponent.js
  pentaho-js/src/test/javascript/cdf/components/TableComponent-spec.js

**Comment by jvelasques** [comment]
@pamval @afrjorge looks good to me

**Pull request merged**
