### PR TITLE
[BACKLOG-6856] Tests for blockUI behaviour

### PR DESCRIPTION
**Pull request by annapopova1**
@diogofscmariano @jvelasques please review

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core-js/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  core-js/src/test/javascript/cdf/dashboard/Dashboard.notifications-spec.js

Newly Fixed Tests:
======================
unit PhantomJS 1.9.8 (Linux 0.0.0).Unmanaged Base Component # Query Lifecycle #.Doesn't overwrite data if postFetch returns undefined:
-----------------------------------------------

```
Expected 1 to equal 2.
Error: Expected 1 to equal 2.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:258

```

```
Expected 1 to equal 2.
Error: Expected 1 to equal 2.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:259

```

```
Expected 1 to equal 2.
Error: Expected 1 to equal 2.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:261

```

```
Expected 1 to equal 2.
Error: Expected 1 to equal 2.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:262

```
unit PhantomJS 1.9.8 (Linux 0.0.0).Unmanaged Base Component # Query Lifecycle #.Only updates once if called concurrently:
-----------------------------------------------

```
Expected 2 to equal 1.
Error: Expected 2 to equal 1.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:295

```

```
Expected 2 to equal 1.
Error: Expected 2 to equal 1.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:297

```

```
Expected 2 to equal 1.
Error: Expected 2 to equal 1.
    at /home/buildguy/project/core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js:298

```

null

null

**Comment by annapopova1** [comment]
@brosander can we restart wingman for this pull-request?

**Comment by krivera-pentaho** [comment]
I am restarting it

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core-js/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js
  core-js/src/test/javascript/cdf/dashboard/Dashboard.notifications-spec.js

null

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core-js/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core-js/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js
  core-js/src/test/javascript/cdf/dashboard/Dashboard.notifications-spec.js

null

null

**Pull request merged**
