### PR TITLE
dataBar alignment

### PR DESCRIPTION
**Pull request by khauser**
I was not able to test this because "cdf-blueprint-style-includes.css" and "cdf-blueprint-script-includes.js" always contain the old code I think. I deleted them and also restarted the server without any changes. Would appretiate your help!

### CODE REVIEW

**Comment by khauser** [comment]
Hm.. js-legacy does not seam to be updated during "ant dist"..

**Comment by pamval** [comment]
created jira issue: http://jira.pentaho.com/browse/CDF-615

**Comment by khauser** [comment]
Sorry, my fault.. I didn't noticed that you are also maintaining some legacy code. I will fix this..

**Comment by khauser** [comment]
image

This is what it looks like now. Headers must be aligned independent.

**Comment by khauser** [comment]
i will renew the PR because of the missing jira case nummers in the commit

**Pull request closed without merging**
