### PR TITLE
[PDB-1901] Filters used in Analyzer reports are not updated when using Dashboard buttons especially when the value of the buttons change

### PR DESCRIPTION
**Pull request by MikhailHubanau**
Added a new case to dashboard.fireChange() call condition in MultiButtonComponent.js#draw() function.

@pamval , @jvelasques please review.

### CODE REVIEW

**Comment by pamval** [comment]
@diogofscmariano @annapopova1 @afrjorge please review

**Comment by diogofscmariano** [comment]
So, this is a case were we are drawing the buttons and in the same moment the first value is different from the one selected? Will this not break the use cases where buttons can have a different default value? Also, maybe it will better to use the !== instead !=. 

Can we have unit tests for this?

**Comment by MikhailHubanau** [comment]
>So, this is a case were we are drawing the buttons and in the same moment the first value is different from the one selected? Will this not break the use cases where buttons can have a different default value? Also, maybe it will better to use the !== instead !=.

I updated PR. @diogofscmariano please take a look.

>Can we have unit tests for this?

No.

**Comment by pamval** [comment]
Why can't we have unit tests?

**Comment by MikhailHubanau** [comment]
I mean that for now we do not have MultiButtonComponent.js#draw() unit test.

**Comment by pamval** [comment]
Have you taken a look at https://github.com/webdetails/cdf/blob/master/core-js/src/test/javascript/cdf/components/MultiButtonComponent-spec.js ?

I don't understand why you can't add an unit test there that covers the behavior you've introduced.
Any call to component.update will lead up to draw being called.

**Comment by MikhailHubanau** [comment]
>Have you taken a look at https://github.com/webdetails/cdf/blob/master/core-js/src/test/javascript/cdf/components/MultiButtonComponent-spec.js ?

Yes.

>I don't understand why you can't add an unit test there that covers the behavior you've introduced.
Any call to component.update will lead up to draw being called.

I am trying to understand how can I check the count of myself.dashboard.fireChange() calls in two cases: myArray.length == 1 and myArray.length != 1, based on current MultiButtonComponent-spec.js code. I accepted that it will looks like 
//init
...
// execute
multiButtonComponent.draw()
//check
...
but test goes through dashboard.update(), I can not get this test mechanism for current moment.

**Comment by MikhailHubanau** [comment]
Added unit test.

**Comment by pamval** [comment]
@diogofscmariano @annapopova1 @afrjorge please review

**Comment by MikhailHubanau** [comment]
@diogofscmariano @annapopova1 @afrjorge please review

**Pull request merged**
